swipe:
  3:
    left:
      command: 'xdotool key alt+Right'  # back
    right:
      command: 'xdotool key alt+Left' # forward
    up:
      command: 'xdotool key ctrl+t' # create tab
    down:
      command: 'xdotool key ctrl+w' # close tab
  4:
    left:
      sendkey: "LEFTCTRL+COMMA"
    right:
      sendkey: "RIGHTCTRL+DOT"
    up:
      command: 'xdotool key super+n'
    down:
      command: 'xdotool key super'
pinch:
  2:
    in:
      command: "xdotool keydown ctrl click 4 keyup ctrl" # threshold: 0.5, interval: 0.5
    out:
      command: "xdotool keydown ctrl click 5 keyup ctrl" # threshold: 0.5, interval: 0.5

threshold:
  pinch: 0.5

interval:
  swipe: 0.75
  pinch: 0.5
